### ISSUE TITLE
identifier might not be what you need to identify transactions per company

### ISSUE THREAD

**Issue by esakal** [GuyLewin/israel-finance-telegram-bot#1]
Hi @GuyLewin 
I love how you integrated the israeli-bank-scrapers to telegram, it seems really handy.

Reading your code, I saw that you are treating the `identifier`  column as a unique value? 
https://github.com/GuyLewin/israel-finance-telegram-bot/blob/70fae63081c7ebcc2da4805d43a65cfb38ab6498/src/index.js#L94
If so you might reconsider it as it doesn't apply to all companies. 

This is an example taken from a one month scraping of my accounts. You can see that there are many without identifier and some that are repeating ones.
![image](https://user-images.githubusercontent.com/4751797/51571934-60dfd200-1eac-11e9-80e5-cd1ed0d6c29e.png)

[identifier column](https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md#overriding-fetchdata) in the scraped accounts refer to `אסמכתא` and every company uses it differently. In bank Leumi for example every transfer to Leumi credit card might get the same identifier value and salaries will also get the same identifier. Leumi card doesn't expose identifier so they will result with empty identifier

Since I only checked one month scraped transactions I only got duplications in Leumi company but it might be enough to reason about it. You can consider extending your calculated identifier. I'm echoing the way YNAB creates its import id per transaction it might be helpful here:
> YNAB:[milliunit_amount]:[iso_date]:[occurrence]'. For example, a transaction dated 2015-12-30 in the amount of -$294.23 USD would have an import_id of 'YNAB:-294230:2015-12-30:1’. If a second transaction on the same account was imported and had the same date and same amount, its import_id would be 'YNAB:-294230:2015-12-30:2’

**Comment by GuyLewin** [comment]
Hey @esakal , thanks for finding this project!
You're very right, I think I'll have time to get into it this weekend or maybe the week after.
Thanks again!

**Comment by GuyLewin** [comment]
Switched to this (I try identifier in case it works, also I don't want to use the number of occurrences since I want to be able to distinguish, obviously):
```javascript
const identifier = `${transaction.date}-${transaction.chargedAmount}-${transaction.identifier}`;
```
