### ISSUE TITLE
Fix the link to the definitions file in Israel-bank-scraper

### ISSUE THREAD

**Issue by podj** [GuyLewin/israel-finance-telegram-bot#11]
The current link in the README is:
https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/definitions.js

But should be:
https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/definitions.ts

(TS not JS)

**Comment by GuyLewin** [comment]
Thanks @podj !
Is there a chance you can create a PR for this? I'll approve it.

**Comment by podj** [comment]
> Thanks @podj !
> Is there a chance you can create a PR for this? I'll approve it.

Sure! I think you'll need to put me as a contributor so I can create a new branch :)

**Comment by GuyLewin** [comment]
> > Thanks @podj !
> > Is there a chance you can create a PR for this? I'll approve it.
> 
> Sure! I think you'll need to put me as a contributor so I can create a new branch :)

You can fork the project and submit a request to merge to "master"

**Comment by podj** [comment]
> > > Thanks @podj !
> > > Is there a chance you can create a PR for this? I'll approve it.
> > 
> > 
> > Sure! I think you'll need to put me as a contributor so I can create a new branch :)
> 
> You can fork the project and submit a request to merge to "master"

https://github.com/GuyLewin/israel-finance-telegram-bot/pull/13

**Comment by GuyLewin** [comment]
Thanks @podj !
