### ISSUE TITLE
Poalim: "scraping failed for the following reason: GENERIC"

### ISSUE THREAD

**Issue by dudutwizer** [GuyLewin/israel-finance-telegram-bot#5]
here is my config.js

 SERVICES: [
    {
      companyId: 'hapoalim',
      niceName: 'בנק הפועלים',
      credentials: {
                userCode: 'username',
                password: 'password',
      },

BTW - Leumi card works just great, thank you for your hard work on this solution.

**Comment by GuyLewin** [comment]
Hi! Thanks for using this project!
This error code comes from the underlaying https://github.com/eshaham/israeli-bank-scrapers project. I noticed I get this error when the credentials are incorrect. Did you make sure the username and password are right?

**Comment by GuyLewin** [comment]
@dudutwizer I have the same issue myself at the moment. We're waiting for release 0.8.1 of `israel-bank-scrapers` to fix that issue. I hope that helps.

**Comment by dmahabad** [comment]
Hi Guy , it seems that the latest version of israel-bank-scrapers fixed that issue (release 0.9.0)

**Comment by GuyLewin** [comment]
@dmahabad yeah, I'll push an update today.

**Comment by GuyLewin** [comment]
Done. Pushed version 2.0.1 to master and updated `:latest` tag on Docker Hub. Now using `israeli-bank-scrapers` 0.9.0.
Let me know if there are any more issues!
