### ISSUE TITLE
Max doesn't work

### ISSUE THREAD

**Issue by DvirNaim** [GuyLewin/israel-finance-telegram-bot#7]
hi

Thanks for the project!

It gave me an error about unknown id "max" which it should know.

I looked into the code and it seems like the scrapers are outdated. 
maybe it's not taking the latest code from https://github.com/eshaham/israeli-bank-scrapers

Thanks! 
Dvir

**Comment by GuyLewin** [comment]
Hey Dvir,

Thanks for using my project!
I actually relocated to US so I didn't get the chance to update the scrapers :)
I'll do it over the weekend I believe or next week. For now - you can use "leumiCard" instead until then.
Are you using the Docker image from Docker Hub?

**Comment by DvirNaim** [comment]
No, actually I'm using the native installation...

indeed, the leumiCard is working 

thanks! :)

**Comment by uptowndat777777** [comment]
Hello, Compliment of the day, how are you today ? i am Happy to get together with you,My name is Serach , I'm a military medical nurse from israel. Please let not my profession, race or nationality inch your mind, I have gone across your profile and became interested in you, we can be good friends, contact me through my private email address/  //abelmans@aol.com   ////
